import { STORAGE_KEYS, readStorage, writeStorage, removeStorage } from "./storage.js";

const DEMO_ACCOUNT = { name: "Demo Explorer", email: "demo@movieverse.local", password: "movieverse" };
export const defaultOnboarding = () => ({ domains: [], languages: [], genres: [], ottPlatforms: [], onboardingCompleted: false });
export const getAccount = () => readStorage(STORAGE_KEYS.account, null) || DEMO_ACCOUNT;
export const getSession = () => readStorage(STORAGE_KEYS.session, null);
export const setSession = (session) => writeStorage(STORAGE_KEYS.session, session);
export const clearSession = () => removeStorage(STORAGE_KEYS.session);
export const passwordRules = (password) => ({ length: password.length >= 8, upper: /[A-Z]/.test(password), lower: /[a-z]/.test(password), number: /\d/.test(password), special: /[^A-Za-z0-9]/.test(password) });
const validEmail = (email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
const fieldError = (form, name, message) => { const target = form.querySelector(`[data-error="${name}"]`); if (target) target.textContent = message; };
const clearMessages = () => document.querySelectorAll(".field-error, .form-error").forEach((element) => { element.textContent = ""; element.classList.remove("success"); });
const showView = (view) => { document.querySelectorAll("[data-auth-form], .forgot-view").forEach((element) => element.classList.remove("active")); document.querySelector(`[data-auth-form="${view}"], [data-view="${view}"]`)?.classList.add("active"); document.querySelectorAll(".auth-tab").forEach((tab) => { const active = tab.dataset.authTab === view; tab.classList.toggle("active", active); tab.setAttribute("aria-selected", String(active)); }); clearMessages(); };
const togglePassword = (button) => { const input = button.parentElement.querySelector("input"); const visible = input.type === "text"; input.type = visible ? "password" : "text"; button.textContent = visible ? "Show" : "Hide"; button.setAttribute("aria-label", visible ? "Show password" : "Hide password"); };
const updateRequirements = (password) => { const rules = passwordRules(password); document.querySelectorAll("[data-password-requirements] [data-rule]").forEach((item) => item.classList.toggle("valid", rules[item.dataset.rule])); const score = Object.values(rules).filter(Boolean).length; const target = document.querySelector(".password-strength"); target.textContent = !password ? "" : score === 5 ? "Strong password" : score >= 3 ? "Good start · keep going" : "Build a stronger password"; target.className = `password-strength ${score === 5 ? "strong" : score >= 3 ? "good" : "weak"}`; };

export function setupAuth({ enterHome, startOnboarding }) {
    document.querySelectorAll("[data-auth-tab]").forEach((tab) => tab.addEventListener("click", () => showView(tab.dataset.authTab)));
    document.querySelectorAll("[data-show-view]").forEach((button) => button.addEventListener("click", () => showView(button.dataset.showView)));
    document.querySelectorAll("[data-password-toggle]").forEach((button) => button.addEventListener("click", () => togglePassword(button)));
    document.querySelectorAll("#signup-form input[name=password]").forEach((input) => input.addEventListener("input", () => updateRequirements(input.value)));
    document.getElementById("signin-form").addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; clearMessages(); const email = form.email.value.trim().toLowerCase(); const password = form.password.value; let valid = true; if (!email) { fieldError(form, "email", "Email is required."); valid = false; } else if (!validEmail(email)) { fieldError(form, "email", "Enter a valid email address."); valid = false; } if (!password) { fieldError(form, "password", "Password is required."); valid = false; } if (!valid) return; const account = getAccount(); if (!account || email !== account.email.trim().toLowerCase() || password !== account.password) { form.querySelector("[data-form-error]").textContent = "Email or password is incorrect."; return; } const onboarding = readStorage(STORAGE_KEYS.onboarding, defaultOnboarding()); setSession({ isAuthenticated: true, isGuest: false, rememberMe: form.remember.checked, currentUser: { name: account.name, email: account.email }, isFirstTimeUser: !onboarding.onboardingCompleted, onboardingCompleted: onboarding.onboardingCompleted }); onboarding.onboardingCompleted ? enterHome() : startOnboarding(onboarding); });
    document.getElementById("signup-form").addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; clearMessages(); const name = form.name.value.trim(); const email = form.email.value.trim().toLowerCase(); const password = form.password.value; const rules = passwordRules(password); let valid = true; if (!name) { fieldError(form, "name", "Your name is required."); valid = false; } if (!email || !validEmail(email)) { fieldError(form, "email", "Enter a valid email address."); valid = false; } if (Object.values(rules).some((rule) => !rule)) { fieldError(form, "password", "Meet every password requirement above."); valid = false; } if (password !== form.confirm.value) { fieldError(form, "confirm", "Passwords do not match."); valid = false; } if (!valid) return; const account = { name, email, password, createdAt: new Date().toISOString() }; writeStorage(STORAGE_KEYS.account, account); writeStorage(STORAGE_KEYS.onboarding, defaultOnboarding()); setSession({ isAuthenticated: true, isGuest: false, rememberMe: false, currentUser: { name, email }, isFirstTimeUser: true, onboardingCompleted: false }); const message = form.querySelector("[data-form-error]"); message.classList.add("success"); message.textContent = "Account created. Let’s personalize your MovieVerse."; setTimeout(() => startOnboarding(defaultOnboarding()), 550); });
    document.getElementById("forgot-form").addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; const message = form.querySelector("[data-form-error]"); if (!validEmail(form.email.value.trim())) { fieldError(form, "forgot-email", "Enter a valid email address."); return; } message.classList.add("success"); message.textContent = "Reset link simulated. No email was sent."; });
    document.querySelector("[data-guest]").addEventListener("click", () => { setSession({ isAuthenticated: true, isGuest: true, currentUser: { name: "Guest Explorer", email: null }, onboardingCompleted: true, isFirstTimeUser: false }); enterHome(); });
}
