import { STORAGE_KEYS, readStorage, writeStorage } from "./storage.js";
import { defaultOnboarding } from "./auth.js";
import { onboardingSteps, nativeLanguageNames } from "./data/onboarding.js";
import { domainVisuals, languageVisuals, genreVisuals, ottVisuals } from "./data/visuals.js";

const visualGroups = { domains: domainVisuals, languages: languageVisuals, genres: genreVisuals, ottPlatforms: ottVisuals };
let state = { step: 0, selections: defaultOnboarding() };
const setText = (selector, value) => { const element = document.querySelector(selector); if (element) element.textContent = value; };
const optionCard = (option, index, step, selected) => { const visual = visualGroups[step.key][option]; const secondary = step.key === "languages" ? `<small>${nativeLanguageNames[option] || "Originals"}</small>` : `<small>${step.key === "ottPlatforms" ? "Preference only" : "Explore this world"}</small>`; return `<button class="selection-card ${selected.includes(option) ? "selected" : ""}" type="button" aria-pressed="${selected.includes(option)}" data-option="${option}" style="--card-image:url('${visual}')" data-option-image="${visual}"><span class="selection-icon">${String(index + 1).padStart(2, "0")}</span><strong>${option}</strong>${secondary}<span class="selection-check" aria-hidden="true">✓</span></button>`; };

function render() { const step = onboardingSteps[state.step]; const complete = state.step === onboardingSteps.length; const grid = document.getElementById("onboarding-options"); setText("#onboarding-step-label", complete ? "STEP 5 OF 5" : `STEP ${state.step + 1} OF 5`); setText("#onboarding-step-count", complete ? "05 / 05" : `0${state.step + 1} / 05`); document.getElementById("onboarding-progress-bar").style.width = `${((state.step + 1) / 5) * 100}%`; if (complete) { document.getElementById("onboarding-shell").dataset.atmosphere = "complete"; setText("#onboarding-title", "Your MovieVerse is ready."); setText("#onboarding-description", "Your preferences are saved. Take a breath, then enter your new entertainment universe."); grid.className = "selection-grid completion-grid step-enter"; grid.innerHTML = '<div class="completion-orbit"><span class="pulse"></span></div><p class="completion-note">Your domains, languages, genres, and platform preferences are ready for future personalization.</p>'; document.getElementById("onboarding-next").disabled = false; document.getElementById("onboarding-next").innerHTML = 'Enter MovieVerse <span>↗</span>'; setText("#selection-hint", "Personalization complete"); document.getElementById("selection-hint").classList.add("valid"); document.getElementById("onboarding-back").classList.add("visible"); document.getElementById("onboarding-back").disabled = false; return; }
    setText("#onboarding-title", step.title); setText("#onboarding-description", step.description); document.getElementById("onboarding-shell").dataset.atmosphere = step.atmosphere; const selected = state.selections[step.key] || []; grid.className = `selection-grid ${step.key}-grid step-enter`; grid.innerHTML = step.options.map((option, index) => optionCard(option, index, step, selected)).join(""); grid.querySelectorAll("[data-option]").forEach((button) => { button.addEventListener("click", () => select(button, step.key)); const image = new Image(); image.onload = () => button.classList.add("has-image"); image.onerror = () => button.classList.add("image-fallback"); image.src = button.dataset.optionImage; }); const enough = selected.length >= step.minimum; setText("#selection-hint", step.hint); document.getElementById("selection-hint").classList.toggle("valid", enough); document.getElementById("onboarding-next").disabled = !enough; document.getElementById("onboarding-next").innerHTML = 'Next <span>→</span>'; document.getElementById("onboarding-back").disabled = state.step === 0; document.getElementById("onboarding-back").classList.toggle("visible", state.step > 0);
}
function select(button, key) { const current = state.selections[key] || []; const value = button.dataset.option; state.selections[key] = current.includes(value) ? current.filter((item) => item !== value) : [...current, value]; const selected = state.selections[key]; button.classList.toggle("selected", selected.includes(value)); button.setAttribute("aria-pressed", String(selected.includes(value))); const valid = selected.length >= onboardingSteps[state.step].minimum; document.getElementById("onboarding-next").disabled = !valid; document.getElementById("selection-hint").classList.toggle("valid", valid); }
export function startOnboarding(saved = readStorage(STORAGE_KEYS.onboarding, defaultOnboarding())) { const { moods, viewingStyle, ...preferences } = saved; state = { step: 0, selections: { ...defaultOnboarding(), ...preferences } }; document.getElementById("auth-shell").hidden = true; document.getElementById("app-shell").hidden = true; document.getElementById("personalization-shell").hidden = true; document.getElementById("onboarding-shell").hidden = false; render(); }
function complete() { writeStorage(STORAGE_KEYS.onboarding, { ...state.selections, onboardingCompleted: true, savedAt: new Date().toISOString() }); document.getElementById("onboarding-shell").hidden = true; document.getElementById("personalization-shell").hidden = false; const stages = ["Understanding your interests...", "Matching your languages...", "Organizing your genres...", "Connecting your OTT preferences...", "Personalizing MovieVerse..."]; let index = 0; const stage = document.getElementById("personalization-stage"); const timer = setInterval(() => { index += 1; if (index < stages.length) stage.textContent = stages[index]; else { clearInterval(timer); document.querySelector(".personalization-dots").hidden = true; stage.hidden = true; document.querySelector(".personalization-ready").hidden = false; } }, 520); }
export function setupOnboarding({ showProfiles, logout }) { document.getElementById("onboarding-next").addEventListener("click", () => state.step === onboardingSteps.length ? complete() : (state.step += 1, render())); document.getElementById("onboarding-back").addEventListener("click", () => { if (state.step > 0) { state.step -= 1; render(); } }); document.querySelectorAll("[data-logout]").forEach((button) => button.addEventListener("click", logout)); document.querySelector("[data-enter-home]").addEventListener("click", showProfiles); }
