import { STORAGE_KEYS, readStorage, writeStorage } from "./storage.js";

const PROFILE_KEY = "movieverse.demo.profiles";
const MAX_PROFILES = 10;
const AVATARS = ["cosmic-01", "cosmic-02", "geo-01", "geo-02", "orbit-01", "orbit-02", "gradient-01", "gradient-02"];
const profileDefaults = (profile = {}) => ({ id: profile.id || `profile-${Date.now()}`, name: profile.name || "", type: profile.type || "standard", avatar: profile.avatar || AVATARS[0], customImage: profile.customImage || null, pin: profile.pin || null, preferences: { domains: [], languages: [], genres: [], ottPlatforms: [], ...(profile.preferences || {}) }, myList: [], wishlist: [], history: [], recentlyViewed: [], continueWatching: [], notifications: [], settings: {}, ...profile });
export const getProfiles = () => readStorage(PROFILE_KEY, []).map(profileDefaults);
export const saveProfiles = (profiles) => writeStorage(PROFILE_KEY, profiles.slice(0, MAX_PROFILES));
export const getActiveProfileId = () => readStorage(STORAGE_KEYS.session, {})?.currentProfileId || null;
export const getActiveProfile = () => getProfiles().find((profile) => profile.id === getActiveProfileId()) || null;
export const profileAvatars = AVATARS;
export const maxProfiles = MAX_PROFILES;

function profileCard(profile, onSelect, onEdit, onDelete) { const card = document.createElement("article"); card.className = "profile-card"; card.innerHTML = `<button class="profile-select" type="button"><span class="profile-avatar avatar-${profile.avatar}" ${profile.customImage ? `style="background-image:url('${profile.customImage}')"` : ""}>${profile.customImage ? "" : profile.name.slice(0, 2).toUpperCase()}</span><strong>${profile.name}</strong><small>${profile.type === "kids" ? "Kids profile" : "Standard profile"}</small></button><div class="profile-card-actions"><button type="button" data-edit>Edit</button><button type="button" data-delete>Delete</button></div>`; card.querySelector(".profile-select").addEventListener("click", () => onSelect(profile)); card.querySelector("[data-edit]").addEventListener("click", () => onEdit(profile)); card.querySelector("[data-delete]").addEventListener("click", () => onDelete(profile)); return card; }
function openProfileShell() { document.getElementById("profile-shell").hidden = false; document.getElementById("auth-shell").hidden = true; document.getElementById("onboarding-shell").hidden = true; document.getElementById("personalization-shell").hidden = true; document.getElementById("app-shell").hidden = true; }
function closeProfileShell() { document.getElementById("profile-shell").hidden = true; }
function setActiveProfile(profile) { const session = readStorage(STORAGE_KEYS.session, {}); writeStorage(STORAGE_KEYS.session, { ...session, currentProfileId: profile.id }); closeProfileShell(); window.dispatchEvent(new CustomEvent("movieverse:profile-selected", { detail: profile })); }
function renderProfiles() { const grid = document.getElementById("profile-grid"); grid.innerHTML = ""; const profiles = getProfiles(); profiles.forEach((profile) => grid.appendChild(profileCard(profile, setActiveProfile, openEditor, deleteProfile))); const add = document.createElement("button"); add.className = "profile-add"; add.type = "button"; add.disabled = profiles.length >= MAX_PROFILES; add.innerHTML = `<span>+</span><strong>${profiles.length >= MAX_PROFILES ? "Profile limit reached" : "Add profile"}</strong><small>${profiles.length} / ${MAX_PROFILES} profiles</small>`; add.addEventListener("click", () => openEditor()); grid.appendChild(add); document.getElementById("profile-count").textContent = `${profiles.length} / ${MAX_PROFILES} PROFILES`; }
function openEditor(profile = null) { const form = document.getElementById("profile-form"); form.reset(); form.dataset.id = profile?.id || ""; form.name.value = profile?.name || ""; form.type.value = profile?.type || "standard"; form.pin.value = profile?.pin || ""; document.querySelectorAll("[data-avatar]").forEach((button) => button.classList.toggle("selected", button.dataset.avatar === (profile?.avatar || AVATARS[0]))); document.getElementById("profile-editor").hidden = false; }
function closeEditor() { document.getElementById("profile-editor").hidden = true; }
function deleteProfile(profile) { if (!window.confirm(`Delete ${profile.name}?`)) return; const profiles = getProfiles().filter((item) => item.id !== profile.id); saveProfiles(profiles); const session = readStorage(STORAGE_KEYS.session, {}); if (session.currentProfileId === profile.id) writeStorage(STORAGE_KEYS.session, { ...session, currentProfileId: profiles[0]?.id || null }); renderProfiles(); }
function setupEditor() { document.querySelectorAll("[data-avatar]").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll("[data-avatar]").forEach((item) => item.classList.remove("selected")); button.classList.add("selected"); })); document.getElementById("profile-cancel").addEventListener("click", closeEditor); document.getElementById("profile-form").addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; const name = form.name.value.trim(); if (!name || name.length > 28) { form.querySelector("[data-error]").textContent = "Enter a profile name up to 28 characters."; return; } const profiles = getProfiles(); const duplicate = profiles.some((profile) => profile.name.toLowerCase() === name.toLowerCase() && profile.id !== form.dataset.id); if (duplicate) { form.querySelector("[data-error]").textContent = "That profile name is already in use."; return; } const selectedAvatar = document.querySelector("[data-avatar].selected")?.dataset.avatar || AVATARS[0]; const next = profileDefaults({ ...(profiles.find((profile) => profile.id === form.dataset.id) || {}), id: form.dataset.id || undefined, name, type: form.type.value, pin: /^\d{4}$/.test(form.pin.value) ? form.pin.value : null, avatar: selectedAvatar }); saveProfiles(form.dataset.id ? profiles.map((profile) => profile.id === form.dataset.id ? next : profile) : [...profiles, next]); closeEditor(); renderProfiles(); }); }
export function setupProfiles({ logout }) { document.getElementById("profile-exit").addEventListener("click", logout); setupEditor(); }
export function showProfiles() { let profiles = getProfiles(); if (!profiles.length && getActiveProfileId() === null) { const session = readStorage(STORAGE_KEYS.session, {}); const guest = profileDefaults({ id: "guest-profile", name: session.isGuest ? "Guest Explorer" : "Main Profile", type: "standard", avatar: "cosmic-01" }); saveProfiles([guest]); const nextSession = { ...session, currentProfileId: guest.id }; writeStorage(STORAGE_KEYS.session, nextSession); profiles = [guest]; } openProfileShell(); renderProfiles(); }
